table T_Utilisateurs_Dim
	lineageTag: 532abb46-bfb6-4099-9d7c-81fee001a836

	column UserID
		dataType: string
		lineageTag: 4a166478-1841-4a09-8ff6-1ee39ede5a40
		summarizeBy: none
		sourceColumn: UserID

		annotation SummarizationSetBy = Automatic

	column DisplayName
		dataType: string
		lineageTag: 7f7a253b-b469-450f-a308-fcadeed7a1d3
		summarizeBy: none
		sourceColumn: DisplayName

		annotation SummarizationSetBy = Automatic

	column UserPrincipalName
		dataType: string
		lineageTag: 4be66fb9-2334-4492-baa7-17a3868eba0b
		summarizeBy: none
		sourceColumn: UserPrincipalName

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: cf4986b4-2fe0-49a5-9c9b-dd40f1b59a01
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column CountryOrRegion
		dataType: string
		lineageTag: fd6858be-b6ab-4353-9626-bbbe5a9e91fb
		summarizeBy: none
		sourceColumn: CountryOrRegion

		annotation SummarizationSetBy = Automatic

	column UsageLocation
		dataType: string
		lineageTag: 9c06f15e-d268-4c9d-a0fb-a4789cae8b87
		summarizeBy: none
		sourceColumn: UsageLocation

		annotation SummarizationSetBy = Automatic

	column UserType
		dataType: string
		lineageTag: 61b6d665-7bb8-4290-a8b9-bba848536e62
		summarizeBy: none
		sourceColumn: UserType

		annotation SummarizationSetBy = Automatic

	column AccountEnabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 51bb3ed6-6e92-4e0b-bba6-45e53fc0263f
		summarizeBy: none
		sourceColumn: AccountEnabled

		annotation SummarizationSetBy = Automatic

	column WhenCreated
		dataType: dateTime
		formatString: General Date
		lineageTag: 7115716f-7c5a-4f00-a32e-df39fadb8353
		summarizeBy: none
		sourceColumn: WhenCreated

		variation Variation
			isDefault
			relationship: c5623bfd-5f5a-4678-aaa1-daf6844f8ec0
			defaultHierarchy: LocalDateTable_ef38b729-9347-4e14-94fc-7178c7b21d1d.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column Licences_Brutes
		dataType: string
		lineageTag: 061193bf-f0ea-44ca-aab2-8395b7aed767
		summarizeBy: none
		sourceColumn: Licences_Brutes

		annotation SummarizationSetBy = Automatic

	column LastSignIn
		dataType: dateTime
		formatString: General Date
		lineageTag: 94811a08-a0c6-47b5-b43e-1787c9d91206
		summarizeBy: none
		sourceColumn: LastSignIn

		variation Variation
			isDefault
			relationship: 71c26b22-d2eb-4145-a044-e3e8279a5884
			defaultHierarchy: LocalDateTable_9c07b0b3-055f-453b-8431-e89adeffbe9c.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column TypeCompte =
			
			VAR Regle = [RegleTypeCompte]
			RETURN
			SWITCH(
			    TRUE(),
			    Regle = "EMPTY", "Non defini",
			    LEFT(Regle, 5) = "TECH_", "Technique",
			    "Utilisateur"
			)
		lineageTag: 4d34890f-8b49-437f-83f2-a2540bc09908
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column EtatActivite =
			
			VAR CodeEtat = [CodeEtatActivite]
			VAR SeuilInactiviteJours =
			    MAXX(T_Parametres_Dim, T_Parametres_Dim[SeuilInactiviteJours])
			VAR LabelInactif =
			    "Inactif >" & FORMAT(SeuilInactiviteJours, "0") & "j"
			
			RETURN
			SWITCH(
			    CodeEtat,
			    "ACTIF", "Actif",
			    "INACTIF", LabelInactif,
			    "JAMAIS_CONNECTE", "Jamais Connect" & UNICHAR(233),
			    "INACTIF_M365", "Inactif M365",
			    "EXCLU", "Exclu",
			    "Exclu"
			)
		lineageTag: 0db36ffc-10e6-4330-ba46-31ff1fa49493
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Statut AD' =
			// Gestion explicite des 3 cas possibles : TRUE, FALSE, et NULL
			SWITCH(
			    TRUE(),
			    'T_Utilisateurs_Dim'[AccountEnabled] = TRUE(), "Activé",
			    'T_Utilisateurs_Dim'[AccountEnabled] = FALSE(), "Désactivé",
			    "Non synchronisé"	// AccountEnabled est NULL dans Azure AD
			)
		lineageTag: b8478b27-741a-46e9-851c-080c3498dfef
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column StatutLicence =
			
			VAR NbLicencesAffectees = COALESCE([NbLicencesAffecteesDistinctes], 0)
			RETURN
			IF(COALESCE(NbLicencesAffectees, 0) > 0, "ON", "OFF")
		lineageTag: 5d4e3984-4f92-4183-88c6-336d621e3362
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Domaine
		dataType: string
		lineageTag: 178a8f11-925d-45b6-bdc0-225f56cfb9d9
		summarizeBy: none
		sourceColumn: Domaine

		annotation SummarizationSetBy = Automatic

	column JoursDepuisConnexion
		dataType: int64
		formatString: 0
		lineageTag: 896cac78-d546-4ce2-853c-82fa6100807c
		summarizeBy: sum
		sourceColumn: JoursDepuisConnexion

		annotation SummarizationSetBy = Automatic

	column IsCible =
			
			// Colonne calculée : identifie les comptes cibles pour le nettoyage
			// Cible = Humain actif AD mais dormant (au-dela du seuil parametre ou jamais connecte) OU tout compte desactive AD
			(
			    T_Utilisateurs_Dim[TypeCompte] = "Utilisateur" &&
			    T_Utilisateurs_Dim[Statut AD] = "Activé" &&
			    T_Utilisateurs_Dim[CodeEtatActivite] IN {"INACTIF", "JAMAIS_CONNECTE"}
			)
			||
			T_Utilisateurs_Dim[Statut AD] = "Désactivé"
		lineageTag: iscible-calc-col-0001-neemba
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DisplayNameAffiche =
			
			VAR _nom = TRIM(COALESCE('T_Utilisateurs_Dim'[DisplayName], ""))
			VAR _upn = TRIM(COALESCE('T_Utilisateurs_Dim'[UserPrincipalName], ""))
			RETURN
			    IF(
			        _nom <> "",
			        _nom,
			        IF(_upn <> "", _upn, "(Sans nom)")
			    )
		lineageTag: a2be7a12-77bf-4582-bdb2-32a6e6b68334
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CodeEtatActivite =
			
			VAR EstTechnique = [TypeCompte] = "Technique"
			VAR EstDesactive = [AccountEnabled] = FALSE()
			VAR UserEmail    = [UserPrincipalName]
			VAR CategorieM365 =
			    LOOKUPVALUE(
			        T_Activite_M365[CategorieActivite],
			        T_Activite_M365[UserPrincipalName], UserEmail
			    )
			VAR AJamaisConnecteAD = ISBLANK([LastSignIn])
			VAR SeuilInactiviteJours =
			    MAXX(T_Parametres_Dim, T_Parametres_Dim[SeuilInactiviteJours])
			VAR LabelInactifM365 =
			    "Inactif (>" & FORMAT(SeuilInactiviteJours, "0") & "j)"
			VAR EstInactif =
			    NOT(ISBLANK([LastSignIn])) && [LastSignIn] < TODAY() - SeuilInactiviteJours
			RETURN
			SWITCH(
			    TRUE(),
			    EstTechnique || EstDesactive, "EXCLU",
			    LEFT(COALESCE(CategorieM365, ""), 6) = "Jamais" && NOT(AJamaisConnecteAD), "INACTIF_M365",
			    LEFT(COALESCE(CategorieM365, ""), 6) = "Jamais", "JAMAIS_CONNECTE",
			    CategorieM365 = LabelInactifM365, "INACTIF",
			    AJamaisConnecteAD, "JAMAIS_CONNECTE",
			    EstInactif, "INACTIF",
			    "ACTIF"
			)
		isHidden
		lineageTag: 2d2c17e8-62df-4a42-8186-cfd18c6919d2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column EstDesactiveAvecLicence =
			
			VAR NbLicencesAffectees = COALESCE([NbLicencesAffecteesDistinctes], 0)
			RETURN
			[TypeCompte] = "Utilisateur"
			    && [AccountEnabled] = FALSE()
			    && COALESCE(NbLicencesAffectees, 0) > 0
		isHidden
		lineageTag: estdesactiveaveclicence-calc-001-neemba
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column RegleTypeCompte =
			
			VAR Nom = LOWER(COALESCE([DisplayName], ""))
			VAR Email = LOWER(COALESCE([UserPrincipalName], ""))
			VAR EstVide = ISBLANK([DisplayName]) && ISBLANK([UserPrincipalName])
			VAR MotConferenceAccent = "conf" & UNICHAR(233) & "rence"
			VAR MotReunionAccent = "r" & UNICHAR(233) & "union"
			VAR MotCongeAccent = "cong" & UNICHAR(233)
			VAR IsGuest = [UserType] = "Guest"
			VAR IsExternal = CONTAINSSTRING(Email, "#ext#")
			VAR IsSharedRoom =
			    LEFT(COALESCE([DisplayName], ""), 1) = "#"
			        || CONTAINSSTRING(Nom, "salle")
			        || CONTAINSSTRING(Nom, "salon")
			        || CONTAINSSTRING(Nom, "meeting")
			        || CONTAINSSTRING(Nom, "conference")
			        || CONTAINSSTRING(Nom, MotConferenceAccent)
			        || CONTAINSSTRING(Nom, "reunion")
			        || CONTAINSSTRING(Nom, MotReunionAccent)
			        || CONTAINSSTRING(Nom, "room")
			        || CONTAINSSTRING(Nom, "boardroom")
			        || CONTAINSSTRING(Nom, "bookings")
			        || CONTAINSSTRING(Nom, "accueil")
			VAR IsGenericEmail =
			    CONTAINSSTRING(Email, "info@")
			        || CONTAINSSTRING(Email, "contact@")
			        || CONTAINSSTRING(Email, "no-reply")
			        || CONTAINSSTRING(Email, "noreply")
			        || CONTAINSSTRING(Email, "norepley")
			        || CONTAINSSTRING(Email, "nepasrepondre")
			        || CONTAINSSTRING(Email, "support@")
			        || CONTAINSSTRING(Email, "catchall")
			        || CONTAINSSTRING(Email, "facture")
			        || CONTAINSSTRING(Email, "export")
			VAR IsSupport =
			    CONTAINSSTRING(Email, "support_")
			        || CONTAINSSTRING(Nom, "support_")
			        || CONTAINSSTRING(Nom, "supportguarani")
			VAR IsInfra =
			    CONTAINSSTRING(Nom, "sql")
			        || CONTAINSSTRING(Nom, "proxy")
			        || CONTAINSSTRING(Nom, "backup")
			        || CONTAINSSTRING(Nom, "sauvegarde")
			        || CONTAINSSTRING(Nom, "ldap")
			        || CONTAINSSTRING(Nom, "utm")
			        || CONTAINSSTRING(Nom, "scan")
			        || CONTAINSSTRING(Nom, "sync")
			        || CONTAINSSTRING(Nom, "bot")
			        || CONTAINSSTRING(Nom, "api")
			        || CONTAINSSTRING(Nom, "svc")
			        || CONTAINSSTRING(Nom, "pool")
			        || CONTAINSSTRING(Nom, "spapp")
			VAR IsAdminPattern =
			    Nom = "admin"
			        || LEFT(Nom, 6) = "admin "
			        || CONTAINSSTRING(Email, "admin@")
			        || CONTAINSSTRING(Email, ".admin@")
			VAR IsPrefix =
			    CONTAINSSTRING(Nom, "app_")
			        || CONTAINSSTRING(Nom, "svc_")
			        || CONTAINSSTRING(Nom, "srv_")
			        || CONTAINSSTRING(Nom, "update")
			        || CONTAINSSTRING(Nom, "irium")
			        || CONTAINSSTRING(Nom, "mts ")
			VAR IsTestPattern =
			    Nom = "test"
			        || LEFT(Nom, 5) = "test "
			        || RIGHT(Nom, 5) = " test"
			VAR IsBI =
			    (LEFT(Nom, 2) = "bo" && LEN(Nom) < 10)
			        || CONTAINSSTRING(Nom, "bodev")
			        || CONTAINSSTRING(Nom, "boprod")
			        || CONTAINSSTRING(Nom, "bosched")
			        || CONTAINSSTRING(Nom, "bosql")
			        || CONTAINSSTRING(Nom, "businessobject")
			        || CONTAINSSTRING(Nom, "powerbi")
			        || CONTAINSSTRING(Nom, "pbi ")
			        || CONTAINSSTRING(Nom, "bi ")
			        || CONTAINSSTRING(Nom, "ireporting")
			        || CONTAINSSTRING(Email, "pbi-")
			        || CONTAINSSTRING(Email, "bi.")
			VAR IsTooling =
			    CONTAINSSTRING(Nom, "azure")
			        || CONTAINSSTRING(Nom, "migration")
			        || CONTAINSSTRING(Nom, "migwiz")
			        || CONTAINSSTRING(Nom, "veeam")
			        || CONTAINSSTRING(Nom, "rubrik")
			        || CONTAINSSTRING(Nom, "sophos")
			        || CONTAINSSTRING(Nom, "sentinel")
			        || CONTAINSSTRING(Nom, "talend")
			        || CONTAINSSTRING(Nom, "mulesoft")
			        || CONTAINSSTRING(Nom, "matrix42")
			        || CONTAINSSTRING(Nom, "m42")
			        || CONTAINSSTRING(Nom, "sage")
			        || CONTAINSSTRING(Nom, "quest")
			        || CONTAINSSTRING(Nom, "coservit")
			        || CONTAINSSTRING(Nom, "projeqtor")
			        || CONTAINSSTRING(Nom, "wordpress")
			        || CONTAINSSTRING(Nom, "systancia")
			        || CONTAINSSTRING(Nom, "aquiweb")
			        || CONTAINSSTRING(Nom, "automator")
			        || CONTAINSSTRING(Nom, "mimecast")
			        || CONTAINSSTRING(Nom, "manageengine")
			        || CONTAINSSTRING(Nom, "rpmglobal")
			        || CONTAINSSTRING(Nom, "svn")
			        || CONTAINSSTRING(Nom, "skype")
			VAR IsNetwork =
			    CONTAINSSTRING(Nom, "xg")
			        || CONTAINSSTRING(Nom, "xcc")
			        || CONTAINSSTRING(Nom, "firewall")
			        || CONTAINSSTRING(Nom, "visor")
			        || CONTAINSSTRING(Nom, "winstox")
			        || CONTAINSSTRING(Nom, "i80")
			VAR IsFormationPattern =
			    Nom = "formation"
			        || LEFT(Nom, 10) = "formation "
			        || CONTAINSSTRING(Email, "formation@")
			VAR IsVisitPattern =
			    Nom = "visit"
			        || LEFT(Nom, 6) = "visit "
			        || Nom = "visitor"
			        || Nom = "visiteur"
			VAR IsBackoffice =
			    CONTAINSSTRING(Nom, "sirh")
			        || CONTAINSSTRING(Nom, "induction")
			        || CONTAINSSTRING(Nom, "reservation")
			        || CONTAINSSTRING(Nom, "validation")
			        || CONTAINSSTRING(Nom, "compta")
			        || CONTAINSSTRING(Nom, MotCongeAccent)
			        || CONTAINSSTRING(Nom, "occasion")
			        || CONTAINSSTRING(Nom, "interfaces")
			        || CONTAINSSTRING(Nom, "intranet")
			        || CONTAINSSTRING(Nom, "supervision")
			        || CONTAINSSTRING(Nom, "operateur")
			        || CONTAINSSTRING(Nom, "gestsup")
			        || CONTAINSSTRING(Nom, "signcenter")
			        || CONTAINSSTRING(Nom, "stagiaire")
			        || CONTAINSSTRING(Nom, "delegues")
			        || CONTAINSSTRING(Nom, "survey")
			VAR IsSpecificEmail =
			    CONTAINSSTRING(Email, "sirh@")
			        || CONTAINSSTRING(Email, ".sirh@")
			        || CONTAINSSTRING(Email, "survey@")
			        || CONTAINSSTRING(Email, "alerts@")
			        || CONTAINSSTRING(Email, "edi@")
			        || CONTAINSSTRING(Email, "-edi@")
			VAR IsShortGeneric =
			    CONTAINSSTRING(Nom, "amt")
			        || CONTAINSSTRING(Nom, "cat")
			        || CONTAINSSTRING(Nom, "cesu")
			        || CONTAINSSTRING(Nom, "dfi")
			        || CONTAINSSTRING(Nom, "bissas")
			        || CONTAINSSTRING(Nom, "qsec")
			        || CONTAINSSTRING(Nom, "scrute")
			        || CONTAINSSTRING(Nom, "suwonda")
			        || CONTAINSSTRING(Nom, "partswe")
			        || CONTAINSSTRING(Nom, "saudequip")
			        || Nom = "su"
			        || Nom = "sac"
			        || Nom = "rcc"
			        || Nom = "ae"
			        || Nom = "dp"
			VAR IsSharedGeneric =
			    CONTAINSSTRING(Nom, "polaris")
			        || CONTAINSSTRING(Nom, "generique")
			        || CONTAINSSTRING(Nom, "partage")
			        || LEFT(Nom, 8) = "service "
			        || Nom = "service"
			        || CONTAINSSTRING(Email, "service@")
			        || CONTAINSSTRING(Email, ".service@")
			RETURN
			SWITCH(
			    TRUE(),
			    EstVide, "EMPTY",
			    IsGuest, "TECH_SIGNAL_GUEST",
			    IsExternal, "TECH_SIGNAL_EXT",
			    IsSharedRoom, "TECH_SHARED_ROOM",
			    IsGenericEmail, "TECH_GENERIC_EMAIL",
			    IsSupport, "TECH_SUPPORT",
			    IsInfra, "TECH_INFRA",
			    IsAdminPattern, "TECH_ADMIN_BOUNDED",
			    IsPrefix, "TECH_PREFIX",
			    IsTestPattern, "TECH_TEST_BOUNDED",
			    IsBI, "TECH_BI",
			    IsTooling, "TECH_TOOLING",
			    IsNetwork, "TECH_NETWORK",
			    IsFormationPattern, "TECH_FORMATION_BOUNDED",
			    IsVisitPattern, "TECH_VISIT_BOUNDED",
			    IsBackoffice, "TECH_BACKOFFICE",
			    IsSpecificEmail, "TECH_EMAIL_SPECIFIC",
			    IsShortGeneric, "TECH_SHORT_GENERIC",
			    IsSharedGeneric, "TECH_SHARED_GENERIC",
			    "USER_DEFAULT"
			)
		isHidden
		lineageTag: regletypecompte-calc-001-neemba
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column NbLicencesAffecteesDistinctes =
			
			VAR _upnNorm = LOWER(TRIM(COALESCE([UserPrincipalName], "")))
			RETURN
			IF(
			    _upnNorm = "",
			    0,
			    CALCULATE(
			        DISTINCTCOUNT(T_Affectations_Fact[AffectationID]),
			        FILTER(
			            ALL(T_Affectations_Fact),
			            LOWER(TRIM(COALESCE(T_Affectations_Fact[UserPrincipalName], ""))) = _upnNorm
			        )
			    )
			)
		isHidden
		lineageTag: nblicencesaffecteesdistinctes-calc-001-neemba
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition T_Utilisateurs_Dim = m
		mode: import
		source = ```
				let
				    // ═══════════════════════════════════════════════════════════════════
				    // 1. SOURCE BRUTE PARTAGÉE
				    // ═══════════════════════════════════════════════════════════════════
				    Source = GetUsersBaseTable,
				
				    // ═══════════════════════════════════════════════════════════════════
				    // 2. CORRECTIONS GÉOGRAPHIQUES
				    // ═══════════════════════════════════════════════════════════════════
				    #"Valeur remplacée" = Table.ReplaceValue(Source, "Senegal", "Sénégal", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée1" = Table.ReplaceValue(#"Valeur remplacée", "Benin", "Bénin", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée2" = Table.ReplaceValue(#"Valeur remplacée1", "Mauritania", "Mauritanie", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée3" = Table.ReplaceValue(#"Valeur remplacée2", "Burkina-Faso", "Burkina Faso", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée4" = Table.ReplaceValue(#"Valeur remplacée3", "Guinea", "Guinée", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée5" = Table.ReplaceValue(#"Valeur remplacée4", "FR", "France", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée6" = Table.ReplaceValue(#"Valeur remplacée5", "Mauritius", "Maurice", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée7" = Table.ReplaceValue(#"Valeur remplacée6", "Côte d'Ivoire", "Côte d'Ivoire", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée8" = Table.ReplaceValue(#"Valeur remplacée7", "Côte***********", "Côte d'Ivoire", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée9" = Table.ReplaceValue(#"Valeur remplacée8", "Côte'Ivoire", "Côte d'Ivoire", Replacer.ReplaceText, {"CountryOrRegion"}),
				
				    // ═══════════════════════════════════════════════════════════════════
				    // 3. NOUVELLES COLONNES CALCULÉES (Phase 3)
				    // ═══════════════════════════════════════════════════════════════════
				    
				    // Extraction du domaine email
				    #"Domaine Ajouté" = Table.AddColumn(
				        #"Valeur remplacée9", 
				        "Domaine", 
				        each 
				            let 
				                email = [UserPrincipalName],
				                parts = Text.Split(email, "@")
				            in 
				                if List.Count(parts) > 1 then parts{1} else null,
				        type text
				    ),
				
				    // Calcul du nombre de jours depuis la dernière connexion
				    #"Jours Ajouté" = Table.AddColumn(
				        #"Domaine Ajouté", 
				        "JoursDepuisConnexion", 
				        each 
				            if [LastSignIn] = null then null
				            else Duration.Days(DateTime.LocalNow() - [LastSignIn]),
				        Int64.Type
				    ),
				
				    // ═══════════════════════════════════════════════════════════════════
				    // 4. RÉORGANISATION DES COLONNES
				    // ═══════════════════════════════════════════════════════════════════
				    #"Colonnes réorganisées" = Table.ReorderColumns(
				        #"Jours Ajouté", 
				        {
				            "UserID", 
				            "DisplayName", 
				            "UserPrincipalName", 
				            "Domaine",
				            "Department", 
				            "CountryOrRegion", 
				            "AccountEnabled", 
				            "WhenCreated", 
				            "LastSignIn", 
				            "JoursDepuisConnexion",
				            "Licences_Brutes"
				        }
				    )
				
				in
				    #"Colonnes réorganisées"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

