table T_Utilisateurs_Dim
	lineageTag: 532abb46-bfb6-4099-9d7c-81fee001a836

	column UserID
		dataType: string
		lineageTag: 4a166478-1841-4a09-8ff6-1ee39ede5a40
		summarizeBy: none
		sourceColumn: UserID

		annotation SummarizationSetBy = Automatic

	column DisplayName
		dataType: string
		lineageTag: 7f7a253b-b469-450f-a308-fcadeed7a1d3
		summarizeBy: none
		sourceColumn: DisplayName

		annotation SummarizationSetBy = Automatic

	column UserPrincipalName
		dataType: string
		lineageTag: 4be66fb9-2334-4492-baa7-17a3868eba0b
		summarizeBy: none
		sourceColumn: UserPrincipalName

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: cf4986b4-2fe0-49a5-9c9b-dd40f1b59a01
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column CountryOrRegion
		dataType: string
		lineageTag: fd6858be-b6ab-4353-9626-bbbe5a9e91fb
		summarizeBy: none
		sourceColumn: CountryOrRegion

		annotation SummarizationSetBy = Automatic

	column UsageLocation
		dataType: string
		lineageTag: 9c06f15e-d268-4c9d-a0fb-a4789cae8b87
		summarizeBy: none
		sourceColumn: UsageLocation

		annotation SummarizationSetBy = Automatic

	column UserType
		dataType: string
		lineageTag: 61b6d665-7bb8-4290-a8b9-bba848536e62
		summarizeBy: none
		sourceColumn: UserType

		annotation SummarizationSetBy = Automatic

	column AccountEnabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 51bb3ed6-6e92-4e0b-bba6-45e53fc0263f
		summarizeBy: none
		sourceColumn: AccountEnabled

		annotation SummarizationSetBy = Automatic

	column WhenCreated
		dataType: dateTime
		formatString: General Date
		lineageTag: 7115716f-7c5a-4f00-a32e-df39fadb8353
		summarizeBy: none
		sourceColumn: WhenCreated

		variation Variation
			isDefault
			relationship: c5623bfd-5f5a-4678-aaa1-daf6844f8ec0
			defaultHierarchy: LocalDateTable_ef38b729-9347-4e14-94fc-7178c7b21d1d.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column Licences_Brutes
		dataType: string
		lineageTag: 061193bf-f0ea-44ca-aab2-8395b7aed767
		summarizeBy: none
		sourceColumn: Licences_Brutes

		annotation SummarizationSetBy = Automatic

	column LastSignIn
		dataType: dateTime
		formatString: General Date
		lineageTag: 94811a08-a0c6-47b5-b43e-1787c9d91206
		summarizeBy: none
		sourceColumn: LastSignIn

		variation Variation
			isDefault
			relationship: 71c26b22-d2eb-4145-a044-e3e8279a5884
			defaultHierarchy: LocalDateTable_9c07b0b3-055f-453b-8431-e89adeffbe9c.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column TypeCompte = ```
			
			// Protection contre les valeurs nulles pour eviter les (Blank)
			VAR Nom = LOWER(COALESCE([DisplayName], ""))
			VAR Email = LOWER(COALESCE([UserPrincipalName], ""))
			VAR _estVide = ISBLANK([DisplayName]) && ISBLANK([UserPrincipalName])
			RETURN
			IF(_estVide, "Non defini",
			SWITCH(
			    TRUE(),

			    // === PRIMARY SIGNAL: userType from Graph API ===
			    [UserType] = "Guest", "Technique",
			    CONTAINSSTRING([UserPrincipalName], "#EXT#"), "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // 1. COMPTES EXTERNES
			    // ═══════════════════════════════════════════════════════════════════
			    CONTAINSSTRING(Email, "#ext#"), "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // 2. COMPTES PARTAGÉS / SALLES
			    // ═══════════════════════════════════════════════════════════════════
			    LEFT([DisplayName], 1) = "#", "Technique",
			    CONTAINSSTRING(Nom, "salle"), "Technique",
			    CONTAINSSTRING(Nom, "salon"), "Technique",
			    CONTAINSSTRING(Nom, "meeting"), "Technique",
			    CONTAINSSTRING(Nom, "conference"), "Technique",
			    CONTAINSSTRING(Nom, "conférence"), "Technique",
			    CONTAINSSTRING(Nom, "réunion"), "Technique",
			    CONTAINSSTRING(Nom, "reunion"), "Technique",
			    CONTAINSSTRING(Nom, "room"), "Technique",
			    CONTAINSSTRING(Nom, "boardroom"), "Technique",
			    CONTAINSSTRING(Nom, "bookings"), "Technique",
			    CONTAINSSTRING(Nom, "accueil"), "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // 3. EMAILS GÉNÉRIQUES / NO-REPLY
			    // ═══════════════════════════════════════════════════════════════════
			    CONTAINSSTRING(Email, "info@"), "Technique",
			    CONTAINSSTRING(Email, "contact@"), "Technique",
			    CONTAINSSTRING(Email, "no-reply"), "Technique",
			    CONTAINSSTRING(Email, "noreply"), "Technique",
			    CONTAINSSTRING(Email, "norepley"), "Technique",
			    CONTAINSSTRING(Email, "nepasrepondre"), "Technique",
			    CONTAINSSTRING(Email, "support@"), "Technique",
			    CONTAINSSTRING(Email, "catchall"), "Technique",
			    CONTAINSSTRING(Email, "facture"), "Technique",
			    CONTAINSSTRING(Email, "export"), "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // 4. PATTERNS SUPPORT
			    // ═══════════════════════════════════════════════════════════════════
			    CONTAINSSTRING(Email, "support_"), "Technique",
			    CONTAINSSTRING(Nom, "support_"), "Technique",
			    CONTAINSSTRING(Nom, "supportguarani"), "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // 5. COMPTES IT / INFRASTRUCTURE
			    // ═══════════════════════════════════════════════════════════════════
			    CONTAINSSTRING(Nom, "sql"), "Technique",
			    CONTAINSSTRING(Nom, "proxy"), "Technique",
			    CONTAINSSTRING(Nom, "backup"), "Technique",
			    CONTAINSSTRING(Nom, "sauvegarde"), "Technique",
			    CONTAINSSTRING(Nom, "ldap"), "Technique",
			    CONTAINSSTRING(Nom, "utm"), "Technique",
			    CONTAINSSTRING(Nom, "scan"), "Technique",
			    CONTAINSSTRING(Nom, "sync"), "Technique",
			    CONTAINSSTRING(Nom, "bot"), "Technique",
			    CONTAINSSTRING(Nom, "api"), "Technique",
			    (Nom = "admin" || LEFT(Nom, 6) = "admin " || CONTAINSSTRING(Email, "admin@") || CONTAINSSTRING(Email, ".admin@")), "Technique",
			    CONTAINSSTRING(Nom, "svc"), "Technique",
			    CONTAINSSTRING(Nom, "pool"), "Technique",
			    CONTAINSSTRING(Nom, "spapp"), "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // 6. PRÉFIXES TECHNIQUES
			    // ═══════════════════════════════════════════════════════════════════
			    CONTAINSSTRING(Nom, "app_"), "Technique",
			    CONTAINSSTRING(Nom, "svc_"), "Technique",
			    CONTAINSSTRING(Nom, "srv_"), "Technique",
			    (Nom = "test" || LEFT(Nom, 5) = "test " || RIGHT(Nom, 5) = " test"), "Technique",
			    CONTAINSSTRING(Nom, "update"), "Technique",
			    CONTAINSSTRING(Nom, "irium"), "Technique",
			    CONTAINSSTRING(Nom, "mts "), "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // 7. BUSINESS OBJECTS / BI
			    // ═══════════════════════════════════════════════════════════════════
			    LEFT(Nom, 2) = "bo" && LEN(Nom) < 10, "Technique",
			    CONTAINSSTRING(Nom, "bodev"), "Technique",
			    CONTAINSSTRING(Nom, "boprod"), "Technique",
			    CONTAINSSTRING(Nom, "bosched"), "Technique",
			    CONTAINSSTRING(Nom, "bosql"), "Technique",
			    CONTAINSSTRING(Nom, "businessobject"), "Technique",
			    CONTAINSSTRING(Nom, "powerbi"), "Technique",
			    CONTAINSSTRING(Nom, "pbi "), "Technique",
			    CONTAINSSTRING(Nom, "bi "), "Technique",
			    CONTAINSSTRING(Nom, "ireporting"), "Technique",
			    CONTAINSSTRING(Email, "pbi-"), "Technique",
			    CONTAINSSTRING(Email, "bi."), "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // 8. OUTILS / APPLICATIONS IT
			    // ═══════════════════════════════════════════════════════════════════
			    CONTAINSSTRING(Nom, "azure"), "Technique",
			    CONTAINSSTRING(Nom, "migration"), "Technique",
			    CONTAINSSTRING(Nom, "migwiz"), "Technique",
			    CONTAINSSTRING(Nom, "veeam"), "Technique",
			    CONTAINSSTRING(Nom, "rubrik"), "Technique",
			    CONTAINSSTRING(Nom, "sophos"), "Technique",
			    CONTAINSSTRING(Nom, "sentinel"), "Technique",
			    CONTAINSSTRING(Nom, "talend"), "Technique",
			    CONTAINSSTRING(Nom, "mulesoft"), "Technique",
			    CONTAINSSTRING(Nom, "matrix42"), "Technique",
			    CONTAINSSTRING(Nom, "m42"), "Technique",
			    CONTAINSSTRING(Nom, "sage"), "Technique",
			    CONTAINSSTRING(Nom, "quest"), "Technique",
			    CONTAINSSTRING(Nom, "coservit"), "Technique",
			    CONTAINSSTRING(Nom, "projeqtor"), "Technique",
			    CONTAINSSTRING(Nom, "wordpress"), "Technique",
			    CONTAINSSTRING(Nom, "systancia"), "Technique",
			    CONTAINSSTRING(Nom, "aquiweb"), "Technique",
			    CONTAINSSTRING(Nom, "automator"), "Technique",
			    CONTAINSSTRING(Nom, "mimecast"), "Technique",
			    CONTAINSSTRING(Nom, "manageengine"), "Technique",
			    CONTAINSSTRING(Nom, "rpmglobal"), "Technique",
			    CONTAINSSTRING(Nom, "svn"), "Technique",
			    CONTAINSSTRING(Nom, "skype"), "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // 9. INFRASTRUCTURE RÉSEAU
			    // ═══════════════════════════════════════════════════════════════════
			    CONTAINSSTRING(Nom, "xg"), "Technique",
			    CONTAINSSTRING(Nom, "xcc"), "Technique",
			    CONTAINSSTRING(Nom, "firewall"), "Technique",
			    CONTAINSSTRING(Nom, "visor"), "Technique",
			    CONTAINSSTRING(Nom, "winstox"), "Technique",
			    CONTAINSSTRING(Nom, "i80"), "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // 10. RH / ADMINISTRATION / GÉNÉRIQUES
			    // ═══════════════════════════════════════════════════════════════════
			    CONTAINSSTRING(Nom, "sirh"), "Technique",
			    (Nom = "formation" || LEFT(Nom, 10) = "formation " || CONTAINSSTRING(Email, "formation@")), "Technique",
			    CONTAINSSTRING(Nom, "induction"), "Technique",
			    CONTAINSSTRING(Nom, "reservation"), "Technique",
			    CONTAINSSTRING(Nom, "validation"), "Technique",
			    CONTAINSSTRING(Nom, "compta"), "Technique",
			    CONTAINSSTRING(Nom, "congé"), "Technique",
			    CONTAINSSTRING(Nom, "occasion"), "Technique",
			    CONTAINSSTRING(Nom, "interfaces"), "Technique",
			    CONTAINSSTRING(Nom, "intranet"), "Technique",
			    CONTAINSSTRING(Nom, "supervision"), "Technique",
			    CONTAINSSTRING(Nom, "operateur"), "Technique",
			    CONTAINSSTRING(Nom, "gestsup"), "Technique",
			    CONTAINSSTRING(Nom, "signcenter"), "Technique",
			    CONTAINSSTRING(Nom, "stagiaire"), "Technique",
			    CONTAINSSTRING(Nom, "delegues"), "Technique",
			    (Nom = "visit" || LEFT(Nom, 6) = "visit " || Nom = "visitor" || Nom = "visiteur"), "Technique",
			    CONTAINSSTRING(Nom, "survey"), "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // 11. PATTERNS EMAIL SPÉCIFIQUES
			    // ═══════════════════════════════════════════════════════════════════
			    CONTAINSSTRING(Email, "sirh@"), "Technique",
			    CONTAINSSTRING(Email, ".sirh@"), "Technique",
			    CONTAINSSTRING(Email, "survey@"), "Technique",
			    CONTAINSSTRING(Email, "alerts@"), "Technique",
			    CONTAINSSTRING(Email, "edi@"), "Technique",
			    CONTAINSSTRING(Email, "-edi@"), "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // 12. COMPTES COURTS / GÉNÉRIQUES (3-4 lettres majuscules)
			    // ═══════════════════════════════════════════════════════════════════
			    CONTAINSSTRING(Nom, "amt"), "Technique",
			    CONTAINSSTRING(Nom, "cat"), "Technique",
			    CONTAINSSTRING(Nom, "cesu"), "Technique",
			    CONTAINSSTRING(Nom, "dfi"), "Technique",
			    CONTAINSSTRING(Nom, "bissas"), "Technique",
			    CONTAINSSTRING(Nom, "qsec"), "Technique",
			    CONTAINSSTRING(Nom, "scrute"), "Technique",
			    CONTAINSSTRING(Nom, "suwonda"), "Technique",
			    CONTAINSSTRING(Nom, "partswe"), "Technique",
			    CONTAINSSTRING(Nom, "saudequip"), "Technique",
			    
			    // Comptes très courts (2-3 lettres seules)
			    Nom = "su", "Technique",
			    Nom = "sac", "Technique",
			    Nom = "rcc", "Technique",
			    Nom = "ae", "Technique",
			    Nom = "dp", "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // 13. COMPTES PARTAGÉS / GÉNÉRIQUES
			    // ═══════════════════════════════════════════════════════════════════
			    CONTAINSSTRING(Nom, "polaris"), "Technique",
			    CONTAINSSTRING(Nom, "generique"), "Technique",
			    CONTAINSSTRING(Nom, "partage"), "Technique",
			    (LEFT(Nom, 8) = "service " || Nom = "service" || CONTAINSSTRING(Email, "service@") || CONTAINSSTRING(Email, ".service@")), "Technique",
			
			    // ═══════════════════════════════════════════════════════════════════
			    // PAR DÉFAUT : UTILISATEUR HUMAIN
			    // ═══════════════════════════════════════════════════════════════════
			    "Utilisateur"
			))
			```
		lineageTag: 4d34890f-8b49-437f-83f2-a2540bc09908
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column EtatActivite =
			
			VAR EstTechnique = [TypeCompte] = "Technique"
			VAR EstDesactive = [AccountEnabled] = FALSE()
			VAR UserEmail    = [UserPrincipalName]
			
			// Catégorie issue des données d'activité Microsoft 365
			VAR CategorieM365 =
			    LOOKUPVALUE(
			        T_Activite_M365[CategorieActivite],
			        T_Activite_M365[UserPrincipalName], UserEmail
			    )
			
			// Connexion Azure AD (authentification, indépendant des apps M365)
			VAR AJamaisConnecteAD = ISBLANK([LastSignIn])
			VAR SeuilInactiviteJours =
			    SELECTEDVALUE(T_Parametres_Dim[SeuilInactiviteJours], 90)
			VAR LabelInactif =
			    "Inactif >" & FORMAT(SeuilInactiviteJours, "0") & "j"
			VAR EstInactif =
			    NOT(ISBLANK([LastSignIn])) && [LastSignIn] < TODAY() - SeuilInactiviteJours
			
			RETURN
			IF(
			    EstTechnique || EstDesactive,
			    "Exclu",	// Remplace BLANK() par une valeur explicite pour eviter les (Blank) dans les filtres
			    IF(
			        NOT(ISBLANK(CategorieM365)),
			        // Nuance : si M365 dit 'Jamais Connecté' mais Azure AD a une connexion
			        // → l'user s'est authentifié mais n'utilise aucune app M365
			        SWITCH(
			            TRUE(),
			            CategorieM365 = "Jamais Connecté" && NOT(AJamaisConnecteAD),
			            "Inactif M365",
			            CategorieM365 = "Inactif (>90j)", LabelInactif,
			            CategorieM365
			        ),
			        // Fallback sur Azure AD si aucune donnée M365
			        IF(
			            AJamaisConnecteAD,
			            "Jamais Connecté",
			            IF(EstInactif, LabelInactif, "Actif")
			        )
			    )
			)
		lineageTag: 0db36ffc-10e6-4330-ba46-31ff1fa49493
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CodeEtatActivite = ```
			
			VAR EstTechnique = [TypeCompte] = "Technique"
			VAR EstDesactive = [AccountEnabled] = FALSE()
			VAR UserEmail    = [UserPrincipalName]
			VAR CategorieM365 =
			    LOOKUPVALUE(
			        T_Activite_M365[CategorieActivite],
			        T_Activite_M365[UserPrincipalName], UserEmail
			    )
			VAR AJamaisConnecteAD = ISBLANK([LastSignIn])
			VAR SeuilInactiviteJours =
			    SELECTEDVALUE(T_Parametres_Dim[SeuilInactiviteJours], 90)
			VAR EstInactif =
			    NOT(ISBLANK([LastSignIn])) && [LastSignIn] < TODAY() - SeuilInactiviteJours
			RETURN
			SWITCH(
			    TRUE(),
			    EstTechnique || EstDesactive, "EXCLU",
			    LEFT(COALESCE(CategorieM365, ""), 6) = "Jamais" && NOT(AJamaisConnecteAD), "INACTIF_M365",
			    LEFT(COALESCE(CategorieM365, ""), 6) = "Jamais", "JAMAIS_CONNECTE",
			    CategorieM365 = "Inactif (>90j)", "INACTIF",
			    AJamaisConnecteAD, "JAMAIS_CONNECTE",
			    EstInactif, "INACTIF",
			    "ACTIF"
			)
			```
		isHidden
		lineageTag: 2d2c17e8-62df-4a42-8186-cfd18c6919d2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Statut AD' =
			// Gestion explicite des 3 cas possibles : TRUE, FALSE, et NULL
			SWITCH(
			    TRUE(),
			    'T_Utilisateurs_Dim'[AccountEnabled] = TRUE(), "Activé",
			    'T_Utilisateurs_Dim'[AccountEnabled] = FALSE(), "Désactivé",
			    "Non synchronisé"	// AccountEnabled est NULL dans Azure AD
			)
		lineageTag: b8478b27-741a-46e9-851c-080c3498dfef
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column StatutLicence = ```
			
			VAR NbLicencesAffectees =
			    CALCULATE(
			        COALESCE(DISTINCTCOUNT(T_Affectations_Fact[AffectationID]), 0)
			    )
			RETURN
			IF(NbLicencesAffectees > 0, "ON", "OFF")
			```
		lineageTag: 5d4e3984-4f92-4183-88c6-336d621e3362
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Domaine
		dataType: string
		lineageTag: 178a8f11-925d-45b6-bdc0-225f56cfb9d9
		summarizeBy: none
		sourceColumn: Domaine

		annotation SummarizationSetBy = Automatic

	column JoursDepuisConnexion
		dataType: int64
		formatString: 0
		lineageTag: 896cac78-d546-4ce2-853c-82fa6100807c
		summarizeBy: sum
		sourceColumn: JoursDepuisConnexion

		annotation SummarizationSetBy = Automatic

	column IsCible =
			
			// Colonne calculée : identifie les comptes cibles pour le nettoyage
			// Cible = Humain actif AD mais dormant (>90j ou jamais connecté) OU tout compte désactivé AD
			(
			    T_Utilisateurs_Dim[TypeCompte] = "Utilisateur" &&
			    T_Utilisateurs_Dim[Statut AD] = "Activé" &&
			    T_Utilisateurs_Dim[CodeEtatActivite] IN {"INACTIF", "JAMAIS_CONNECTE"}
			)
			||
			T_Utilisateurs_Dim[Statut AD] = "Désactivé"
		lineageTag: iscible-calc-col-0001-neemba
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DisplayNameAffiche =
			
			VAR _nom = TRIM(COALESCE('T_Utilisateurs_Dim'[DisplayName], ""))
			VAR _upn = TRIM(COALESCE('T_Utilisateurs_Dim'[UserPrincipalName], ""))
			RETURN
			    IF(
			        _nom <> "",
			        _nom,
			        IF(_upn <> "", _upn, "(Sans nom)")
			    )
		lineageTag: a2be7a12-77bf-4582-bdb2-32a6e6b68334
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition T_Utilisateurs_Dim = m
		mode: import
		source = ```
				let
				    // ═══════════════════════════════════════════════════════════════════
				    // 1. AUTHENTIFICATION SÉCURISÉE (Via Paramètres)
				    // ═══════════════════════════════════════════════════════════════════
				    TenantId = Text.From(#"Param_TenantId"),
				    ClientId = Text.From(#"Param_ClientId"),
				    ClientSecret = Text.From(#"Param_Secret"),
				
				    GetAccessToken = () =>
				        let
				            Url = "https://login.microsoftonline.com/" & TenantId & "/oauth2/v2.0/token",
				            Body = "client_id=" & ClientId & 
				                   "&scope=https://graph.microsoft.com/.default" & 
				                   "&client_secret=" & Uri.EscapeDataString(ClientSecret) & 
				                   "&grant_type=client_credentials",
				            Response = Json.Document(
				                Web.Contents(Url, [
				                    Headers = [#"Content-Type" = "application/x-www-form-urlencoded"], 
				                    Content = Text.ToBinary(Body)
				                ])
				            ),
				            Token = "Bearer " & Response[access_token]
				        in
				            Token,
				
				    AuthToken = GetAccessToken(),
				
				    // ═══════════════════════════════════════════════════════════════════
				    // 2. URL CIBLE (API BETA pour signInActivity)
				    // ═══════════════════════════════════════════════════════════════════
				    BaseUrl = "https://graph.microsoft.com/beta/users?" 
				              & "$top=999&" 
				              & "$select=id,displayName,userPrincipalName,department,country,"
				              & "usageLocation,userType,accountEnabled,assignedLicenses,createdDateTime,signInActivity",
				
				    // ═══════════════════════════════════════════════════════════════════
				    // 3. PAGINATION
				    // ═══════════════════════════════════════════════════════════════════
				    FetchPage = (url) =>
				        let
				            RawData = Json.Document(Web.Contents(url, [Headers = [Authorization = AuthToken]])),
				            NextLink = try RawData[#"@odata.nextLink"] otherwise null,
				            Data = try RawData[value] otherwise null
				        in
				            [Data = Data, Next = NextLink],
				
				    AllPages = List.Generate(
				        () => FetchPage(BaseUrl),
				        each [Data] <> null,
				        each FetchPage([Next]),
				        each [Data]
				    ),
				
				    // ═══════════════════════════════════════════════════════════════════
				    // 4. TRANSFORMATION EN TABLE
				    // ═══════════════════════════════════════════════════════════════════
				    CombinedList = List.Combine(AllPages),
				    Tabled = Table.FromList(CombinedList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    Expanded = Table.ExpandRecordColumn(
				        Tabled, 
				        "Column1", 
				        {"id", "displayName", "userPrincipalName", "department", "country", "usageLocation", "userType", "accountEnabled", "createdDateTime", "signInActivity", "assignedLicenses"},
				        {"UserID", "DisplayName", "UserPrincipalName", "Department", "CountryOrRegion", "UsageLocation", "UserType", "AccountEnabled", "WhenCreated", "signInActivity", "Licences_Brutes"}
				    ),
				
				    // ═══════════════════════════════════════════════════════════════════
				    // 5. CALCUL DE LA DERNIÈRE ACTIVITÉ
				    // ═══════════════════════════════════════════════════════════════════
				    #"LastSignIn Ajouté" = Table.AddColumn(
				        Expanded, 
				        "LastSignIn", 
				        each 
				            if [signInActivity] <> null then 
				                let
				                    Interactive = try Record.Field([signInActivity], "lastSignInDateTime") otherwise null,
				                    NonInteractive = try Record.Field([signInActivity], "lastNonInteractiveSignInDateTime") otherwise null,
				                    DateList = List.RemoveNulls({Interactive, NonInteractive}),
				                    MaxDate = if List.IsEmpty(DateList) then null else List.Max(DateList)
				                in 
				                    MaxDate
				            else 
				                null
				    ),
				
				    #"Colonnes supprimées" = Table.RemoveColumns(#"LastSignIn Ajouté", {"signInActivity"}),
				
				    // ═══════════════════════════════════════════════════════════════════
				    // 6. TYPAGE INITIAL
				    // ═══════════════════════════════════════════════════════════════════
				    #"Type modifié" = Table.TransformColumnTypes(
				        #"Colonnes supprimées",
				        {
				            {"UsageLocation", type text},
				            {"UserType", type text},
				            {"WhenCreated", type datetime}, 
				            {"LastSignIn", type datetime}, 
				            {"AccountEnabled", type logical}
				        }
				    ),
				
				    // ═══════════════════════════════════════════════════════════════════
				    // 7. CORRECTIONS GÉOGRAPHIQUES
				    // ═══════════════════════════════════════════════════════════════════
				    #"Valeur remplacée" = Table.ReplaceValue(#"Type modifié", "Senegal", "Sénégal", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée1" = Table.ReplaceValue(#"Valeur remplacée", "Benin", "Bénin", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée2" = Table.ReplaceValue(#"Valeur remplacée1", "Mauritania", "Mauritanie", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée3" = Table.ReplaceValue(#"Valeur remplacée2", "Burkina-Faso", "Burkina Faso", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée4" = Table.ReplaceValue(#"Valeur remplacée3", "Guinea", "Guinée", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée5" = Table.ReplaceValue(#"Valeur remplacée4", "FR", "France", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée6" = Table.ReplaceValue(#"Valeur remplacée5", "Mauritius", "Maurice", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée7" = Table.ReplaceValue(#"Valeur remplacée6", "Côte d'Ivoire", "Côte d'Ivoire", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée8" = Table.ReplaceValue(#"Valeur remplacée7", "Côte***********", "Côte d'Ivoire", Replacer.ReplaceText, {"CountryOrRegion"}),
				    #"Valeur remplacée9" = Table.ReplaceValue(#"Valeur remplacée8", "Côte'Ivoire", "Côte d'Ivoire", Replacer.ReplaceText, {"CountryOrRegion"}),
				
				    // ═══════════════════════════════════════════════════════════════════
				    // 8. NOUVELLES COLONNES CALCULÉES (Phase 3)
				    // ═══════════════════════════════════════════════════════════════════
				    
				    // Extraction du domaine email
				    #"Domaine Ajouté" = Table.AddColumn(
				        #"Valeur remplacée9", 
				        "Domaine", 
				        each 
				            let 
				                email = [UserPrincipalName],
				                parts = Text.Split(email, "@")
				            in 
				                if List.Count(parts) > 1 then parts{1} else null,
				        type text
				    ),
				
				    // Calcul du nombre de jours depuis la dernière connexion
				    #"Jours Ajouté" = Table.AddColumn(
				        #"Domaine Ajouté", 
				        "JoursDepuisConnexion", 
				        each 
				            if [LastSignIn] = null then null
				            else Duration.Days(DateTime.LocalNow() - [LastSignIn]),
				        Int64.Type
				    ),
				
				    // ═══════════════════════════════════════════════════════════════════
				    // 9. RÉORGANISATION DES COLONNES
				    // ═══════════════════════════════════════════════════════════════════
				    #"Colonnes réorganisées" = Table.ReorderColumns(
				        #"Jours Ajouté", 
				        {
				            "UserID", 
				            "DisplayName", 
				            "UserPrincipalName", 
				            "Domaine",
				            "Department", 
				            "CountryOrRegion", 
				            "AccountEnabled", 
				            "WhenCreated", 
				            "LastSignIn", 
				            "JoursDepuisConnexion",
				            "Licences_Brutes"
				        }
				    )
				
				in
				    #"Colonnes réorganisées"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

